import json
from typing import Dict, Any, Optional
from app.models.es_types import DiagnosticResult, FixProposal
from app.services.inference import inference_service

class FixGenerator:
    """
    Orchestrates the logic to generate valid Elasticsearch DSL fixes.
    """
    
    async def generate_fix(self, diagnostic: DiagnosticResult) -> FixProposal:
        category = diagnostic.category
        
        # 1. Prepare Context
        # CRITICAL: We explicitly capture the index name here
        affected_resource = diagnostic.affected_resource 
        
        context = f"Issue: {diagnostic.description}. Severity: {diagnostic.severity}."
        
        # 2. Call LLM (or Fallback)
        llm_response = await inference_service.generate_fix_proposal(context, affected_resource)
        
        # 3. Extract parts
        fixed_code = llm_response.get("fixed_code", {})
        explanation = llm_response.get("explanation", "Generated by Auto-Fixer Agent.")
        
        # 4. Construct Proposal
        # LOGICAL FIX: We pass 'index' explicitly in original_code so Validator finds it 100% of the time.
        return FixProposal(
            issue_id=diagnostic.issue_id,
            original_code={
                "source": str(affected_resource),
                "index": affected_resource,  # <--- THIS IS THE MISSING KEY
                "category": category
            },
            fixed_code=fixed_code,
            explanation=explanation,
            estimated_impact="High - AI optimized."
        )

# Singleton instance
fix_generator = FixGenerator()